Adding new Makefile and TARGET dependend compilation

diff --git a/pci/pc-pci/Makefile b/pci/pc-pci/Makefile
--- a/pci/pc-pci/Makefile
+++ b/pci/pc-pci/Makefile
@@ -1,35 +1,47 @@
 #
-# Phoenix-RTOS
+# Makefile for Phoenix-RTOS pc-tty drivers
 #
-# pc-uart - PC serial port driver
+# Copyright 2017, 2018 Phoenix Systems
+# Copyright 2001, 2005-2006 Pawel Pisarczyk
 #
-# Copyright 2017 Phoenix Systems
-# Author: Pawel Pisarczyk
-#
-CROSS ?= i386-pc-phoenix-
-
-CC = $(CROSS)gcc
-CFLAGS = -m32 -fstack-protector -c -Wall -O2 -g\
-	 -I. -I../../../../libphoenix/ -I../../../../phoenix-rtos-kernel/src\
-	 -DARCH=\"arch/ia32/arch.h\"\
-	 -DHAL=\"hal//ia32//hal.h\"
-
-
-LD = $(CROSS)gcc
-LDFLAGS = -m32 -nostdlib -nostartfiles -static
 
 SRCS = pc-pci.c
 OBJS = $(SRCS:.c=.o)
-GCCLIB := $(shell $(CC) $(CFLAGS) -print-libgcc-file-name)
 BIN = pc-pci
 
-all: pc-pci test_pci
+CFLAGS += -I. -I../../../libphoenix/ -DARCH=\"arch/ia32/arch.h\"
+
+
+all: check $(BIN)
+
+
+check:
+	@(if test -z "$(TARGET)"; then\
+		echo "Error: Only main Makefile can be used for compilation!";\
+		exit 1;\
+	fi;)
+
 
 .c.o:
-	$(CC) $(CFLAGS) $<
+	@(printf " CC    %-24s  \n" "$<"; $(CC) -c $(CFLAGS) $<)
 
-pc-pci: $(OBJS)
-	$(LD) $(LDFLAGS) -o $(BIN) $(OBJS) ../../../../libphoenix/libphoenix.a $(GCCLIB)
+-include .depend
 
-clean:
-	rm -f *.o *~ core
+
+$(BIN): $(OBJS)
+	@echo " LD    $@"
+	$(SIL)$(LD) -o $(BIN) $(OBJS) ../../../libphoenix/libphoenix.a $(GCCLIB)
+	@echo " STRIP $@"
+	$(SIL)$(STRIP) $(BIN) 2>/dev/null
+
+
+depend: check
+	$(SIL)$(MKDEP) $(MKDEPFLAGS) $(SRCS) >.depend
+
+
+clean: check
+	$(SIL)rm -f core *.o $(ARCH)
+
+
+.PHONY: clean
+# DO NOT DELETE
diff --git a/storage/ata/Makefile b/storage/ata/Makefile
--- a/storage/ata/Makefile
+++ b/storage/ata/Makefile
@@ -1,33 +1,47 @@
 #
-# Phoenix-RTOS
+# Makefile for Phoenix-RTOS pc-ata driver
 #
-# descriptions
+# Copyright 2017, 2018 Phoenix Systems
+# Copyright 2001, 2005-2006 Pawel Pisarczyk
 #
-# Copyright 2017 Phoenix Systems
-# Author: Pawel Pisarczyk
-#
-
-CC = gcc
-CFLAGS = -m32 -c -Wall -O2 -g -I. -I../../../libphoenix/ -DARCH=\"arch/ia32/arch.h\"\
-			-DHAL=\"hal//ia32//hal.h\" \
-			-I../../../phoenix-rtos-kernel/src/ -I../../bus/pci/pc-pci/
-
-LD = gcc
-LDFLAGS = -m32 -nostdlib -nostartfiles -static
-#-z max-page-size=0x10000
 
 SRCS = pc-ata.c
 OBJS = $(SRCS:.c=.o)
-GCCLIB := $(shell $(CC) $(CFLAGS) -print-libgcc-file-name)
 BIN = pc-ata
 
-all: pc-ata
+CFLAGS += -I. -I../../../libphoenix/ -I../../pci/pc-pci -DARCH=\"arch/ia32/arch.h\"
+
+
+all: check $(BIN)
+
+
+check:
+	@(if test -z "$(TARGET)"; then\
+		echo "Error: Only main Makefile can be used for compilation!";\
+		exit 1;\
+	fi;)
+
 
 .c.o:
-	$(CC) $(CFLAGS) $<
+	@(printf " CC    %-24s  \n" "$<"; $(CC) -c $(CFLAGS) $<)
 
-pc-ata: $(OBJS)
-	$(LD) $(LDFLAGS) -o $(BIN) $(OBJS) ../../../libphoenix/libphoenix.a $(GCCLIB)
+-include .depend
 
-clean:
-	rm -f *.o *~ core
+
+$(BIN): $(OBJS)
+	@echo " LD    $@"
+	$(SIL)$(LD) -o $(BIN) $(OBJS) ../../../libphoenix/libphoenix.a $(GCCLIB)
+	@echo " STRIP $@"
+	$(SIL)$(STRIP) $(BIN) 2>/dev/null
+
+
+depend: check
+	$(SIL)$(MKDEP) $(MKDEPFLAGS) $(SRCS) >.depend
+
+
+clean: check
+	$(SIL)rm -f core *.o $(ARCH)
+
+
+.PHONY: clean
+# DO NOT DELETE
diff --git a/storage/imx6ull-flash/Makefile b/storage/imx6ull-flash/Makefile
--- a/storage/imx6ull-flash/Makefile
+++ b/storage/imx6ull-flash/Makefile
@@ -1,55 +1,46 @@
 #
-# Makefile for IMX6ULL flash driver
+# Makefile for Phoenix-RTOS imx6ull-uart driver
 #
-# Copyright 2017 Phoenix Systems
-#
-# %LICENSE%
+# Copyright 2018 Phoenix Systems
 #
 
-SIL ?= @
+SRCS = flashdrv.c
+OBJS = $(SRCS:.c=.o)
+BIN = flashdrv
 
-CROSS ?= arm-phoenix-
-SUBDIRS = arch/arm-imx $(SUBSYSTEMS)
+CFLAGS += -I. -I../../../libphoenix -I../../../phoenix-rtos-kernel/include
 
-MKDEP = $(CROSS)gcc -MM
-MKDEPFLAGS = $(CFLAGS)
 
-CC = $(CROSS)gcc
+all: check $(BIN)
 
-SRCDIR=$(CURDIR)
-LIBPHOENIX=../../../libphoenix
-LIB=$(LIBPHOENIX)/libphoenix.a
-KERNELHEADERS=../../../phoenix-rtos-kernel/include
 
-CFLAGS += -Os -Wall -Wstrict-prototypes -g -I$(SRCDIR) -I$(LIBPHOENIX) -I$(KERNELHEADERS) -nostartfiles -nostdlib\
-	-mcpu=cortex-a7 -mtune=cortex-a7 -mfloat-abi=hard -mthumb\
-	-fomit-frame-pointer -ffreestanding -mno-unaligned-access\
-	-DVERSION=\"$(VERSION)\" -DARCH=\"arch/arm-imx/arch.h\"
+check:
+	@(if test -z "$(TARGET)"; then\
+		echo "Error: Only main Makefile can be used for compilation!";\
+		exit 1;\
+	fi;)
 
-AR = $(CROSS)ar
-ARFLAGS = -r
-
-LD = $(CROSS)ld
-LDFLAGS = -nostdlib -z max-page-size=0x1000
-GCCLIB := $(shell $(CC) $(CFLAGS) -print-libgcc-file-name)
-
-OBJCOPY = $(CROSS)objcopy
-OBJDUMP = $(CROSS)objdump
-STRIP = $(CROSS)strip
-
-OBJECTS = flashdrv.o
-
-all: flashdrv.elf
-
-flashdrv.elf: $(OBJECTS)
-	$(SIL)(printf "LD  %-24s  \n" "$(OBJECTS)"; $(LD) $(LDFLAGS) -o $@_unstripped $(OBJECTS) $(LIB) $(GCCLIB))
-	$(SIL)($(STRIP) $@_unstripped -o $@)
 
 .c.o:
-	$(SIL)(printf "CC  %-24s  \n" "$<"; $(CC) -c $(CFLAGS) $<)
+	@(printf " CC    %-24s  \n" "$<"; $(CC) -c $(CFLAGS) $<)
 
-clean:
-	$(SIL)rm -f *.o *.elf
+-include .depend
+
+
+$(BIN): $(OBJS)
+	@echo " LD    $@"
+	$(SIL)$(LD) -o $(BIN) $(OBJS) ../../../libphoenix/libphoenix.a $(GCCLIB)
+	@echo " STRIP $@"
+	$(SIL)$(STRIP) $(BIN) 2>/dev/null
+
+
+depend: check
+	$(SIL)$(MKDEP) $(MKDEPFLAGS) $(SRCS) >.depend
+
+
+clean: check
+	$(SIL)rm -f core *.o $(ARCH)
+
 
 .PHONY: clean
 # DO NOT DELETE
diff --git a/tty/imx6ull-uart/Makefile b/tty/imx6ull-uart/Makefile
--- a/tty/imx6ull-uart/Makefile
+++ b/tty/imx6ull-uart/Makefile
@@ -1,38 +1,46 @@
 #
-# Phoenix-RTOS
-#
-# uart  - i.MX6ULL uart driver
+# Makefile for Phoenix-RTOS imx6ull-uart driver
 #
 # Copyright 2018 Phoenix Systems
-# Author: Kamil Amanowicz
 #
 
-CC = arm-phoenix-gcc
-CFLAGS = -mthumb -c -Wall -Os -nostartfiles -nostdlib -mno-unaligned-access -mcpu=cortex-a7 -mtune=cortex-a7 -mfloat-abi=hard -fomit-frame-pointer -ffreestanding -I. -I../../../libphoenix/ -I../../../phoenix-rtos-kernel/src/ -DARCH=\"arch/arm-imx/arch.h\"
-
-LD = arm-phoenix-gcc
-LDFLAGS = -nostdlib -z max-page-size=0x1000
-
-STRIP = arm-phoenix-strip
-
-SRCS = uartdrv.c
+SRCS = imx6ull-uart.c
 OBJS = $(SRCS:.c=.o)
+BIN = imx6ull-uart
 
-LIBPHOENIX = ../../../libphoenix/libphoenix.a
-GCCLIB := $(shell $(CC) $(CFLAGS) -print-libgcc-file-name)
-BIN = imx-uart
+CFLAGS += -I. -I../../../libphoenix
 
-all: imx-uart imx-uart.debug
+
+all: check $(BIN)
+
+
+check:
+	@(if test -z "$(TARGET)"; then\
+		echo "Error: Only main Makefile can be used for compilation!";\
+		exit 1;\
+	fi;)
+
 
 .c.o:
-	$(CC) $(CFLAGS) $<
+	@(printf " CC    %-24s  \n" "$<"; $(CC) -c $(CFLAGS) $<)
 
-imx-uart: $(OBJS) $(LIBPHOENIX)
-	$(LD) $(LDFLAGS) -o $(BIN) $(OBJS) $(LIBPHOENIX) $(GCCLIB)
-	$(STRIP) $(BIN)
+-include .depend
 
-imx-uart.debug: $(OBJS) $(LIBPHOENIX)
-	$(LD) $(LDFLAGS) -o $(BIN).debug $(OBJS) $(LIBPHOENIX) $(GCCLIB)
 
-clean:
-	rm -f *.o *~ core
+$(BIN): $(OBJS)
+	@echo " LD    $@"
+	$(SIL)$(LD) -o $(BIN) $(OBJS) ../../../libphoenix/libphoenix.a $(GCCLIB)
+	@echo " STRIP $@"
+	$(SIL)$(STRIP) $(BIN) 2>/dev/null
+
+
+depend: check
+	$(SIL)$(MKDEP) $(MKDEPFLAGS) $(SRCS) >.depend
+
+
+clean: check
+	$(SIL)rm -f core *.o $(ARCH)
+
+
+.PHONY: clean
+# DO NOT DELETE
diff --git a/tty/pc-tty/Makefile b/tty/pc-tty/Makefile
--- a/tty/pc-tty/Makefile
+++ b/tty/pc-tty/Makefile
@@ -1,33 +1,47 @@
 #
-# Phoenix-RTOS
+# Makefile for Phoenix-RTOS pc-tty drivers
 #
-# ttypc - VT220 terminal emulator based on VGA and 101-key US keyboard
+# Copyright 2017, 2018 Phoenix Systems
+# Copyright 2001, 2005-2006 Pawel Pisarczyk
 #
-# Copyright 2017 Phoenix Systems
-# Author: Pawel Pisarczyk
-#
-
-CC = i386-pc-phoenix-gcc
-CFLAGS = -c -Wall -O2 -g -I. -I../../../libphoenix/ -DARCH=\"arch/ia32/arch.h\"
-
-LD = i386-pc-phoenix-gcc
-LDFLAGS = -nostartfiles -nostdlib
-
-STRIP = i386-pc-phoenix-strip
 
 SRCS = ttypc.c ttypc_virt.c ttypc_vtf.c ttypc_vga.c ttypc_kbd.c
 OBJS = $(SRCS:.c=.o)
-GCCLIB := $(shell $(CC) $(CFLAGS) -print-libgcc-file-name)
 BIN = pc-tty
 
-all: pc-tty
+CFLAGS += -I. -I../../../libphoenix/ -DARCH=\"arch/ia32/arch.h\"
+
+
+all: check $(BIN)
+
+
+check:
+	@(if test -z "$(TARGET)"; then\
+		echo "Error: Only main Makefile can be used for compilation!";\
+		exit 1;\
+	fi;)
+
 
 .c.o:
-	$(CC) $(CFLAGS) $<
+	@(printf " CC    %-24s  \n" "$<"; $(CC) -c $(CFLAGS) $<)
 
-pc-tty: $(OBJS)
-	$(LD) $(LDFLAGS) -o $(BIN) $(OBJS) ../../../libphoenix/libphoenix.a $(GCCLIB)
-	$(STRIP) $(BIN)
+-include .depend
 
-clean:
-	rm -f *.o *~ core
+
+$(BIN): $(OBJS)
+	@echo " LD    $@"
+	$(SIL)$(LD) -o $(BIN) $(OBJS) ../../../libphoenix/libphoenix.a $(GCCLIB)
+	@echo " STRIP $@"
+	$(SIL)$(STRIP) $(BIN) 2>/dev/null
+
+
+depend: check
+	$(SIL)$(MKDEP) $(MKDEPFLAGS) $(SRCS) >.depend
+
+
+clean: check
+	$(SIL)rm -f core *.o $(ARCH)
+
+
+.PHONY: clean
+# DO NOT DELETE
